# Lab 3 - KNN

## Setup

In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 

## Load and Look at Data

In [11]:
iris = datasets.load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

## Get X, Y, Names from Dataset

In [17]:
x = iris.data
y = iris.target
names_array = iris.target_names
print(x)
print(y)
print(names_array)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

## Split Data into Train/Test (80/20)

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=81)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

[[6.1 3.  4.9 1.8]
 [5.  3.2 1.2 0.2]
 [6.7 3.  5.  1.7]
 [6.3 2.3 4.4 1.3]
 [4.8 3.1 1.6 0.2]
 [4.9 3.6 1.4 0.1]
 [5.9 3.  5.1 1.8]
 [5.1 2.5 3.  1.1]
 [7.  3.2 4.7 1.4]
 [6.9 3.1 5.4 2.1]
 [4.8 3.4 1.6 0.2]
 [6.4 2.8 5.6 2.2]
 [6.6 2.9 4.6 1.3]
 [5.5 2.3 4.  1.3]
 [5.2 3.4 1.4 0.2]
 [5.4 3.9 1.3 0.4]
 [5.5 2.4 3.8 1.1]
 [6.3 2.5 4.9 1.5]
 [6.  2.2 4.  1. ]
 [6.2 2.2 4.5 1.5]
 [6.1 2.8 4.7 1.2]
 [6.9 3.1 5.1 2.3]
 [6.8 2.8 4.8 1.4]
 [5.7 3.8 1.7 0.3]
 [6.9 3.1 4.9 1.5]
 [7.7 2.8 6.7 2. ]
 [4.9 3.1 1.5 0.2]
 [6.  3.4 4.5 1.6]
 [5.5 2.4 3.7 1. ]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [5.7 2.8 4.5 1.3]
 [6.4 2.8 5.6 2.1]
 [4.9 3.  1.4 0.2]
 [7.6 3.  6.6 2.1]
 [6.7 3.  5.2 2.3]
 [5.4 3.4 1.7 0.2]
 [6.1 2.8 4.  1.3]
 [4.4 2.9 1.4 0.2]
 [6.4 2.7 5.3 1.9]
 [5.1 3.5 1.4 0.3]
 [4.4 3.  1.3 0.2]
 [5.7 2.8 4.1 1.3]
 [4.7 3.2 1.3 0.2]
 [5.6 2.8 4.9 2. ]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.3 3.3 6.  2.5]
 [5.1 3.3 1.7 0.5]
 [4.8 3.  1.4 0.3]
 [6.5 3.  5.8 2.2]
 [6.8 3.2 5.9 2.3]
 [6.3 2.9 5.

## Fit KNN Alogorithm (K = 7)

In [18]:
knn_7 = KNeighborsClassifier(n_neighbors=7)
knn_7.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=7)

## Run Predictions on Testing Set

In [22]:
print(y_test)
print(names_array)

[2 0 2 1 0 0 1 0 2 0 1 1 2 2 0 2 0 0 0 1 1 1 0 0 1 1 1 2 0 0]
['setosa' 'versicolor' 'virginica']


In [20]:
y_test_pred = knn_7.predict(x_test)
print(y_test_pred)

[2 0 2 1 0 0 1 0 2 0 1 1 2 2 0 2 0 0 0 1 1 1 0 0 1 1 1 2 0 0]


## Evaluate Model

In [26]:
confusion_matrix(y_test, y_test_pred)

array([[13,  0,  0],
       [ 0, 10,  0],
       [ 0,  0,  7]])

In [27]:
report = classification_report(y_test, y_test_pred, target_names=names_array)
print(report)

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        13
  versicolor       1.00      1.00      1.00        10
   virginica       1.00      1.00      1.00         7

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



## Trying with fewer neighbors (K = 3)

In [28]:
knn_3 = KNeighborsClassifier(n_neighbors=3)
knn_3.fit(x_train, y_train)

y_test_pred_3 = knn_3.predict(x_test)
print(y_test_pred_3)

[2 0 2 1 0 0 1 0 2 0 1 1 2 2 0 2 0 0 0 1 1 1 0 0 1 1 1 2 0 0]


In [29]:
confusion_matrix(y_test, y_test_pred_3)

array([[13,  0,  0],
       [ 0, 10,  0],
       [ 0,  0,  7]])

In [30]:
report_3 = classification_report(y_test, y_test_pred, target_names=names_array)
print(report_3)

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        13
  versicolor       1.00      1.00      1.00        10
   virginica       1.00      1.00      1.00         7

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

