# CPTR 512 Programming in Data Analytics

Harvey Alférez, PhD

## Unit 6. Supervised learning. Session 1

This unit is organized as follows:
    
- Classifying with k-Nearest Neighbors.pdf
- Classification evaluation.pdf
- The example source code explained in the presentations is below...

## KNN

In [1]:
import kNN

group,labels = kNN.createDataSet()
print(group)
print(labels)


[[1.  1.1]
 [1.  1. ]
 [0.  0. ]
 [0.  0.1]]
['A', 'A', 'B', 'B']


In [2]:
kNN.classify0([0,0], group, labels, 3)

'B'

In [3]:
datingDataMat,datingLabels = kNN.file2matrix("datingTestSet2.txt")
print(datingDataMat)
print(datingLabels[0:20])

[[4.0920000e+04 8.3269760e+00 9.5395200e-01]
 [1.4488000e+04 7.1534690e+00 1.6739040e+00]
 [2.6052000e+04 1.4418710e+00 8.0512400e-01]
 ...
 [2.6575000e+04 1.0650102e+01 8.6662700e-01]
 [4.8111000e+04 9.1345280e+00 7.2804500e-01]
 [4.3757000e+04 7.8826010e+00 1.3324460e+00]]
['3', '2', '1', '1', '1', '1', '3', '3', '1', '3', '1', '1', '2', '1', '1', '1', '1', '1', '2', '3']


In [4]:
normMat = kNN.autoNorm(datingDataMat)
normMat

(array([[0.44832535, 0.39805139, 0.56233353],
        [0.15873259, 0.34195467, 0.98724416],
        [0.28542943, 0.06892523, 0.47449629],
        ...,
        [0.29115949, 0.50910294, 0.51079493],
        [0.52711097, 0.43665451, 0.4290048 ],
        [0.47940793, 0.3768091 , 0.78571804]]),
 array([9.1273000e+04, 2.0919349e+01, 1.6943610e+00]),
 array([0.      , 0.      , 0.001156]))

In [5]:
kNN.classifyPerson()

percentage of time spent playing video games? 3
frequent flier miles earned per year? 2500
liters of ice cream consumed per year? 1


You will probably like this person:  in small doses


In [6]:
kNN.datingClassTest()

the classifier came back with: 3, the real answer is: 3
the classifier came back with: 2, the real answer is: 2
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 2, the real answer is: 2
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answe

In [1]:
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]
#!pip install sklearn
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y)
print(neigh.predict([[1.1]]))
print(neigh.predict_proba([[0.9]]))

[0]
[[0.66666667 0.33333333]]


## Data splitting

In [2]:
#From: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)
print(X)
print(list(y))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[8 9]
 [4 5]
 [0 1]
 [6 7]]
[4, 2, 0, 3]
[[2 3]]
[1]


## Model evaluation

In [4]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 
y_true = [0, 1, 2, 2, 2]
y_pred = [0, 0, 2, 2, 1]
target_names = ['class 0', 'class 1', 'class 2'] 
confusion_matrix(y_true, y_pred)
print(classification_report(y_true, y_pred, target_names=target_names))

#Precision: How often a classifier is right when it says something is fraud?
#Recall: How much of the actual fraud we correctly detect


#Precision example for class 0: true positives / (true positives + false positives) 
#                               = 1 / (1 + 1)  = 0.5

#Recall example for class 0: true positives / (true positives + false negatives)
#                            = 1 / (1 + 0) = 1    
    
#Accuracy: 3 correct classifications / 5 classifications = 0.6
#Macro avg: e.g. f1-score = (0.67 + 0.00 + 0.80)/3 = 0.49
#Weighted avg: e.g. f1-score = (0.67 * (0.2... just 1 sample is from class 0 in y_true) 
#                              + 0.00 * (0.2) + 0.80 * (0.6)) = 0.61 

              precision    recall  f1-score   support

     class 0       0.50      1.00      0.67         1
     class 1       0.00      0.00      0.00         1
     class 2       1.00      0.67      0.80         3

    accuracy                           0.60         5
   macro avg       0.50      0.56      0.49         5
weighted avg       0.70      0.60      0.61         5

